name: Deploy tune.kvoid.net

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-tune
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "."
          target: "/var/www/tune.kvoid.net"
          overwrite: true

      - name: Post-deploy tasks
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            set -e
            sudo mkdir -p /var/www/tune.kvoid.net
            sudo rm -rf /var/www/tune.kvoid.net/.git /var/www/tune.kvoid.net/.github || true
            sudo chown -R www-data:www-data /var/www/tune.kvoid.net
            sudo nginx -t && sudo systemctl reload nginx || true

